/*
===============================================================================
Construction Management System - SQL Server Initial Database
VB.NET Desktop + ASP.NET Core Web API + Mobile Customer Portal
SQL Server 2019/2022+
===============================================================================
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO
IF DB_ID(N'ConstructionManagementDB') IS NULL CREATE DATABASE ConstructionManagementDB;
GO
USE ConstructionManagementDB;
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/* Schemas */
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'Security') EXEC(N'CREATE SCHEMA Security');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'Core') EXEC(N'CREATE SCHEMA Core');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'Projects') EXEC(N'CREATE SCHEMA Projects');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'Finance') EXEC(N'CREATE SCHEMA Finance');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'Files') EXEC(N'CREATE SCHEMA Files');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'Communication') EXEC(N'CREATE SCHEMA Communication');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'Audit') EXEC(N'CREATE SCHEMA Audit');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'App') EXEC(N'CREATE SCHEMA App');
GO

/* Core */
CREATE TABLE Core.Currencies(
 CurrencyCode CHAR(3) NOT NULL PRIMARY KEY,
 NameAr NVARCHAR(100) NOT NULL,
 NameEn NVARCHAR(100) NULL,
 DecimalDigits TINYINT NOT NULL DEFAULT 2,
 IsActive BIT NOT NULL DEFAULT 1
);
CREATE TABLE Core.Companies(
 CompanyId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyCode NVARCHAR(30) NOT NULL UNIQUE,
 NameAr NVARCHAR(200) NOT NULL,
 NameEn NVARCHAR(200) NULL,
 LegalName NVARCHAR(300) NULL,
 RegistrationNumber NVARCHAR(100) NULL,
 TaxNumber NVARCHAR(100) NULL,
 Phone NVARCHAR(50) NULL,
 Mobile NVARCHAR(50) NULL,
 WhatsAppNumber NVARCHAR(50) NULL,
 Email NVARCHAR(200) NULL,
 Website NVARCHAR(300) NULL,
 Address NVARCHAR(500) NULL,
 City NVARCHAR(100) NULL,
 Country NVARCHAR(100) NOT NULL DEFAULT N'Iraq',
 DefaultCurrencyCode CHAR(3) NOT NULL DEFAULT 'IQD',
 TimeZoneId NVARCHAR(100) NOT NULL DEFAULT N'Asia/Baghdad',
 IsActive BIT NOT NULL DEFAULT 1,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 RowVersion ROWVERSION,
 CONSTRAINT FK_Companies_Currency FOREIGN KEY(DefaultCurrencyCode) REFERENCES Core.Currencies(CurrencyCode)
);
CREATE TABLE Core.Branches(
 BranchId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NOT NULL,
 BranchCode NVARCHAR(30) NOT NULL,
 NameAr NVARCHAR(150) NOT NULL,
 NameEn NVARCHAR(150) NULL,
 Phone NVARCHAR(50) NULL,
 Address NVARCHAR(500) NULL,
 City NVARCHAR(100) NULL,
 IsHeadOffice BIT NOT NULL DEFAULT 0,
 IsActive BIT NOT NULL DEFAULT 1,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 RowVersion ROWVERSION,
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 UNIQUE(CompanyId,BranchCode)
);
CREATE TABLE Core.UnitsOfMeasure(
 UnitId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 Code NVARCHAR(30) NOT NULL UNIQUE,
 NameAr NVARCHAR(100) NOT NULL,
 NameEn NVARCHAR(100) NULL,
 IsActive BIT NOT NULL DEFAULT 1
);
CREATE TABLE Core.ProjectStatuses(
 ProjectStatusId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 Code NVARCHAR(50) NOT NULL UNIQUE,
 NameAr NVARCHAR(100) NOT NULL,
 NameEn NVARCHAR(100) NULL,
 SortOrder INT NOT NULL DEFAULT 0,
 IsSystem BIT NOT NULL DEFAULT 0,
 IsActive BIT NOT NULL DEFAULT 1
);
CREATE TABLE Core.ExpenseCategories(
 ExpenseCategoryId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NULL,
 Code NVARCHAR(50) NOT NULL,
 NameAr NVARCHAR(150) NOT NULL,
 NameEn NVARCHAR(150) NULL,
 ScopeType TINYINT NOT NULL DEFAULT 1, -- 1 Both, 2 Project, 3 Company
 IsActive BIT NOT NULL DEFAULT 1,
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId)
);
GO

/* Security */
CREATE TABLE Security.Roles(
 RoleId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 RoleCode NVARCHAR(50) NOT NULL UNIQUE,
 NameAr NVARCHAR(100) NOT NULL,
 NameEn NVARCHAR(100) NULL,
 IsSystemRole BIT NOT NULL DEFAULT 0,
 IsActive BIT NOT NULL DEFAULT 1,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME()
);
CREATE TABLE Security.Permissions(
 PermissionId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 PermissionCode NVARCHAR(100) NOT NULL UNIQUE,
 NameAr NVARCHAR(150) NOT NULL,
 NameEn NVARCHAR(150) NULL,
 ModuleName NVARCHAR(100) NULL,
 IsActive BIT NOT NULL DEFAULT 1
);
CREATE TABLE Security.RolePermissions(
 RoleId UNIQUEIDENTIFIER NOT NULL,
 PermissionId UNIQUEIDENTIFIER NOT NULL,
 PRIMARY KEY(RoleId,PermissionId),
 FOREIGN KEY(RoleId) REFERENCES Security.Roles(RoleId),
 FOREIGN KEY(PermissionId) REFERENCES Security.Permissions(PermissionId)
);
CREATE TABLE Security.Users(
 UserId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NULL,
 BranchId UNIQUEIDENTIFIER NULL,
 CustomerId UNIQUEIDENTIFIER NULL,
 UserName NVARCHAR(100) NOT NULL UNIQUE,
 NormalizedUserName NVARCHAR(100) NOT NULL UNIQUE,
 Email NVARCHAR(200) NULL,
 NormalizedEmail NVARCHAR(200) NULL,
 Phone NVARCHAR(50) NULL,
 PasswordHash NVARCHAR(1000) NULL,
 FullNameAr NVARCHAR(200) NOT NULL,
 FullNameEn NVARCHAR(200) NULL,
 UserType TINYINT NOT NULL DEFAULT 1, -- 1 Company, 2 Customer
 FailedLoginCount INT NOT NULL DEFAULT 0,
 LockoutEndUtc DATETIME2(0) NULL,
 LastLoginUtc DATETIME2(0) NULL,
 IsEmailConfirmed BIT NOT NULL DEFAULT 0,
 IsPhoneConfirmed BIT NOT NULL DEFAULT 0,
 IsLocked BIT NOT NULL DEFAULT 0,
 IsActive BIT NOT NULL DEFAULT 1,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 RowVersion ROWVERSION,
 CHECK(UserType IN(1,2)),
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(BranchId) REFERENCES Core.Branches(BranchId)
);
CREATE TABLE Security.UserRoles(
 UserId UNIQUEIDENTIFIER NOT NULL,
 RoleId UNIQUEIDENTIFIER NOT NULL,
 CompanyId UNIQUEIDENTIFIER NULL,
 BranchId UNIQUEIDENTIFIER NULL,
 PRIMARY KEY(UserId,RoleId),
 FOREIGN KEY(UserId) REFERENCES Security.Users(UserId),
 FOREIGN KEY(RoleId) REFERENCES Security.Roles(RoleId),
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(BranchId) REFERENCES Core.Branches(BranchId)
);
CREATE TABLE Security.RefreshTokens(
 RefreshTokenId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 UserId UNIQUEIDENTIFIER NOT NULL,
 TokenHash VARBINARY(64) NOT NULL,
 ExpiresAtUtc DATETIME2(0) NOT NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 RevokedAtUtc DATETIME2(0) NULL,
 ReplacedByTokenId UNIQUEIDENTIFIER NULL,
 DeviceInfo NVARCHAR(500) NULL,
 IpAddress NVARCHAR(64) NULL,
 FOREIGN KEY(UserId) REFERENCES Security.Users(UserId),
 FOREIGN KEY(ReplacedByTokenId) REFERENCES Security.RefreshTokens(RefreshTokenId)
);
CREATE TABLE Security.UserDevices(
 UserDeviceId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 UserId UNIQUEIDENTIFIER NOT NULL,
 DeviceType TINYINT NOT NULL, -- 1 desktop, 2 android, 3 ios, 4 web
 DeviceName NVARCHAR(150) NULL,
 PushToken NVARCHAR(1000) NULL,
 Platform NVARCHAR(50) NULL,
 AppVersion NVARCHAR(50) NULL,
 LastSeenUtc DATETIME2(0) NULL,
 IsActive BIT NOT NULL DEFAULT 1,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(UserId) REFERENCES Security.Users(UserId)
);
CREATE TABLE Security.PasswordResetTokens(
 PasswordResetTokenId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 UserId UNIQUEIDENTIFIER NOT NULL,
 TokenHash VARBINARY(64) NOT NULL,
 ExpiresAtUtc DATETIME2(0) NOT NULL,
 UsedAtUtc DATETIME2(0) NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(UserId) REFERENCES Security.Users(UserId)
);
GO

/* Customers and contractors */
CREATE TABLE Core.Customers(
 CustomerId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NOT NULL,
 BranchId UNIQUEIDENTIFIER NULL,
 CustomerCode NVARCHAR(50) NOT NULL,
 CustomerType TINYINT NOT NULL DEFAULT 1, -- 1 Person, 2 Company
 FullNameAr NVARCHAR(250) NOT NULL,
 FullNameEn NVARCHAR(250) NULL,
 NationalId NVARCHAR(100) NULL,
 CompanyRegistration NVARCHAR(100) NULL,
 TaxNumber NVARCHAR(100) NULL,
 Phone NVARCHAR(50) NULL,
 AlternatePhone NVARCHAR(50) NULL,
 WhatsAppNumber NVARCHAR(50) NULL,
 Email NVARCHAR(200) NULL,
 Address NVARCHAR(500) NULL,
 City NVARCHAR(100) NULL,
 Notes NVARCHAR(2000) NULL,
 IsActive BIT NOT NULL DEFAULT 1,
 CreatedByUserId UNIQUEIDENTIFIER NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 RowVersion ROWVERSION,
 CHECK(CustomerType IN(1,2)),
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(BranchId) REFERENCES Core.Branches(BranchId),
 FOREIGN KEY(CreatedByUserId) REFERENCES Security.Users(UserId),
 UNIQUE(CompanyId,CustomerCode)
);
GO
-- Add customer FK now that Customers exists.
ALTER TABLE Security.Users WITH CHECK ADD CONSTRAINT FK_Users_Customer FOREIGN KEY(CustomerId) REFERENCES Core.Customers(CustomerId);
GO
CREATE TABLE Core.Contractors(
 ContractorId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NOT NULL,
 ContractorCode NVARCHAR(50) NOT NULL,
 ContractorType TINYINT NOT NULL DEFAULT 1,
 NameAr NVARCHAR(250) NOT NULL,
 NameEn NVARCHAR(250) NULL,
 NationalId NVARCHAR(100) NULL,
 RegistrationNumber NVARCHAR(100) NULL,
 TaxNumber NVARCHAR(100) NULL,
 Phone NVARCHAR(50) NULL,
 WhatsAppNumber NVARCHAR(50) NULL,
 Email NVARCHAR(200) NULL,
 Address NVARCHAR(500) NULL,
 Notes NVARCHAR(2000) NULL,
 IsActive BIT NOT NULL DEFAULT 1,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 RowVersion ROWVERSION,
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 UNIQUE(CompanyId,ContractorCode)
);
GO

/* Projects */
CREATE TABLE Projects.Projects(
 ProjectId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NOT NULL,
 BranchId UNIQUEIDENTIFIER NULL,
 CustomerId UNIQUEIDENTIFIER NOT NULL,
 ProjectStatusId UNIQUEIDENTIFIER NOT NULL,
 ProjectCode NVARCHAR(50) NOT NULL,
 ProjectName NVARCHAR(250) NOT NULL,
 ProjectType NVARCHAR(100) NULL,
 Description NVARCHAR(MAX) NULL,
 Address NVARCHAR(500) NULL,
 City NVARCHAR(100) NULL,
 Country NVARCHAR(100) NOT NULL DEFAULT N'Iraq',
 Latitude DECIMAL(10,7) NULL,
 Longitude DECIMAL(10,7) NULL,
 ContractCurrencyCode CHAR(3) NOT NULL DEFAULT 'IQD',
 EstimatedBudget DECIMAL(19,4) NULL,
 OriginalContractValue DECIMAL(19,4) NULL,
 CurrentContractValue DECIMAL(19,4) NULL,
 StartDate DATE NULL,
 PlannedEndDate DATE NULL,
 ActualEndDate DATE NULL,
 OverallProgressPercent DECIMAL(5,2) NOT NULL DEFAULT 0,
 GeneralNotes NVARCHAR(4000) NULL,
 IsArchived BIT NOT NULL DEFAULT 0,
 CreatedByUserId UNIQUEIDENTIFIER NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 RowVersion ROWVERSION,
 CHECK(OverallProgressPercent BETWEEN 0 AND 100),
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(BranchId) REFERENCES Core.Branches(BranchId),
 FOREIGN KEY(CustomerId) REFERENCES Core.Customers(CustomerId),
 FOREIGN KEY(ProjectStatusId) REFERENCES Core.ProjectStatuses(ProjectStatusId),
 FOREIGN KEY(ContractCurrencyCode) REFERENCES Core.Currencies(CurrencyCode),
 FOREIGN KEY(CreatedByUserId) REFERENCES Security.Users(UserId),
 UNIQUE(CompanyId,ProjectCode)
);
CREATE TABLE Projects.ProjectTeam(
 ProjectTeamId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ProjectId UNIQUEIDENTIFIER NOT NULL,
 UserId UNIQUEIDENTIFIER NOT NULL,
 TeamRole NVARCHAR(100) NULL,
 StartDate DATE NULL,
 EndDate DATE NULL,
 IsPrimary BIT NOT NULL DEFAULT 0,
 IsActive BIT NOT NULL DEFAULT 1,
 FOREIGN KEY(ProjectId) REFERENCES Projects.Projects(ProjectId),
 FOREIGN KEY(UserId) REFERENCES Security.Users(UserId),
 UNIQUE(ProjectId,UserId)
);
CREATE TABLE Projects.ContractorAssignments(
 ContractorAssignmentId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ProjectId UNIQUEIDENTIFIER NOT NULL UNIQUE,
 ContractorId UNIQUEIDENTIFIER NOT NULL,
 CompensationType TINYINT NOT NULL DEFAULT 1, -- 1 Percentage, 2 Fixed, 3 StageBased
 PercentageValue DECIMAL(9,4) NULL,
 FixedAmount DECIMAL(19,4) NULL,
 CurrencyCode CHAR(3) NOT NULL DEFAULT 'IQD',
 Notes NVARCHAR(2000) NULL,
 StartDate DATE NULL,
 EndDate DATE NULL,
 IsActive BIT NOT NULL DEFAULT 1,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 RowVersion ROWVERSION,
 CHECK(CompensationType IN(1,2,3)),
 CHECK((CompensationType=1 AND PercentageValue IS NOT NULL AND PercentageValue BETWEEN 0 AND 100 AND FixedAmount IS NULL)
    OR(CompensationType=2 AND FixedAmount IS NOT NULL AND FixedAmount>=0 AND PercentageValue IS NULL)
    OR(CompensationType=3 AND PercentageValue IS NULL AND FixedAmount IS NULL)),
 FOREIGN KEY(ProjectId) REFERENCES Projects.Projects(ProjectId),
 FOREIGN KEY(ContractorId) REFERENCES Core.Contractors(ContractorId),
 FOREIGN KEY(CurrencyCode) REFERENCES Core.Currencies(CurrencyCode)
);
CREATE TABLE Projects.ProjectStages(
 StageId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ProjectId UNIQUEIDENTIFIER NOT NULL,
 StageCode NVARCHAR(50) NULL,
 StageNameAr NVARCHAR(200) NOT NULL,
 StageNameEn NVARCHAR(200) NULL,
 Description NVARCHAR(2000) NULL,
 ParentStageId UNIQUEIDENTIFIER NULL,
 SortOrder INT NOT NULL DEFAULT 0,
 WeightPercent DECIMAL(9,4) NULL,
 ProgressCalculationMode TINYINT NOT NULL DEFAULT 1, -- 1 Manual, 2 Weighted, 3 Average, 4 Custom
 PlannedStartDate DATE NULL,
 PlannedEndDate DATE NULL,
 ActualStartDate DATE NULL,
 ActualEndDate DATE NULL,
 ProgressPercent DECIMAL(5,2) NOT NULL DEFAULT 0,
 IsCustomerVisible BIT NOT NULL DEFAULT 1,
 IsActive BIT NOT NULL DEFAULT 1,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 RowVersion ROWVERSION,
 CHECK(ProgressPercent BETWEEN 0 AND 100),
 CHECK(WeightPercent IS NULL OR WeightPercent>=0),
 CHECK(ProgressCalculationMode IN(1,2,3,4)),
 FOREIGN KEY(ProjectId) REFERENCES Projects.Projects(ProjectId),
 FOREIGN KEY(ParentStageId) REFERENCES Projects.ProjectStages(StageId)
);
CREATE TABLE Projects.StageWorkItems(
 WorkItemId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 StageId UNIQUEIDENTIFIER NOT NULL,
 WorkItemCode NVARCHAR(50) NULL,
 WorkNameAr NVARCHAR(250) NOT NULL,
 WorkNameEn NVARCHAR(250) NULL,
 Description NVARCHAR(2000) NULL,
 UnitId UNIQUEIDENTIFIER NULL,
 PlannedQuantity DECIMAL(19,4) NULL,
 CompletedQuantity DECIMAL(19,4) NULL,
 UnitPrice DECIMAL(19,4) NULL,
 PlannedCost DECIMAL(19,4) NULL,
 ActualCost DECIMAL(19,4) NULL,
 WeightPercent DECIMAL(9,4) NULL,
 ProgressPercent DECIMAL(5,2) NOT NULL DEFAULT 0,
 SortOrder INT NOT NULL DEFAULT 0,
 IsCustomerVisible BIT NOT NULL DEFAULT 1,
 IsActive BIT NOT NULL DEFAULT 1,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 RowVersion ROWVERSION,
 CHECK(ProgressPercent BETWEEN 0 AND 100),
 CHECK((PlannedQuantity IS NULL OR PlannedQuantity>=0) AND (CompletedQuantity IS NULL OR CompletedQuantity>=0)),
 FOREIGN KEY(StageId) REFERENCES Projects.ProjectStages(StageId),
 FOREIGN KEY(UnitId) REFERENCES Core.UnitsOfMeasure(UnitId)
);
CREATE TABLE Projects.ProgressUpdates(
 ProgressUpdateId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ProjectId UNIQUEIDENTIFIER NOT NULL,
 StageId UNIQUEIDENTIFIER NULL,
 WorkItemId UNIQUEIDENTIFIER NULL,
 ProgressPercent DECIMAL(5,2) NULL,
 UpdateDate DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 Title NVARCHAR(250) NULL,
 Description NVARCHAR(4000) NULL,
 CustomerVisible BIT NOT NULL DEFAULT 1,
 PublishedAtUtc DATETIME2(0) NULL,
 CreatedByUserId UNIQUEIDENTIFIER NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 RowVersion ROWVERSION,
 CHECK(ProgressPercent IS NULL OR ProgressPercent BETWEEN 0 AND 100),
 FOREIGN KEY(ProjectId) REFERENCES Projects.Projects(ProjectId),
 FOREIGN KEY(StageId) REFERENCES Projects.ProjectStages(StageId),
 FOREIGN KEY(WorkItemId) REFERENCES Projects.StageWorkItems(WorkItemId),
 FOREIGN KEY(CreatedByUserId) REFERENCES Security.Users(UserId)
);
CREATE TABLE Projects.Milestones(
 MilestoneId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ProjectId UNIQUEIDENTIFIER NOT NULL,
 StageId UNIQUEIDENTIFIER NULL,
 NameAr NVARCHAR(250) NOT NULL,
 NameEn NVARCHAR(250) NULL,
 Description NVARCHAR(2000) NULL,
 PlannedDate DATE NULL,
 ActualDate DATE NULL,
 Status TINYINT NOT NULL DEFAULT 1,
 CustomerVisible BIT NOT NULL DEFAULT 1,
 SortOrder INT NOT NULL DEFAULT 0,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(ProjectId) REFERENCES Projects.Projects(ProjectId),
 FOREIGN KEY(StageId) REFERENCES Projects.ProjectStages(StageId)
);
GO

/* Contracts / change orders */
CREATE TABLE Projects.Contracts(
 ContractId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ProjectId UNIQUEIDENTIFIER NOT NULL,
 ContractNumber NVARCHAR(50) NOT NULL,
 ContractDate DATE NULL,
 ContractType TINYINT NOT NULL DEFAULT 1,
 OriginalValue DECIMAL(19,4) NOT NULL,
 CurrentValue DECIMAL(19,4) NOT NULL,
 CurrencyCode CHAR(3) NOT NULL,
 PlannedStartDate DATE NULL,
 PlannedEndDate DATE NULL,
 ActualStartDate DATE NULL,
 ActualEndDate DATE NULL,
 TermsAndConditions NVARCHAR(MAX) NULL,
 Status TINYINT NOT NULL DEFAULT 1,
 IsPrimary BIT NOT NULL DEFAULT 1,
 CreatedByUserId UNIQUEIDENTIFIER NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 RowVersion ROWVERSION,
 CHECK(OriginalValue>=0 AND CurrentValue>=0),
 CHECK(Status IN(1,2,3,4)),
 FOREIGN KEY(ProjectId) REFERENCES Projects.Projects(ProjectId),
 FOREIGN KEY(CurrencyCode) REFERENCES Core.Currencies(CurrencyCode),
 FOREIGN KEY(CreatedByUserId) REFERENCES Security.Users(UserId),
 UNIQUE(ProjectId,ContractNumber)
);
CREATE TABLE Projects.ContractVersions(
 ContractVersionId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ContractId UNIQUEIDENTIFIER NOT NULL,
 VersionNumber INT NOT NULL,
 VersionDate DATE NOT NULL DEFAULT CONVERT(date,SYSUTCDATETIME()),
 VersionTitle NVARCHAR(250) NULL,
 ContractValue DECIMAL(19,4) NOT NULL,
 Notes NVARCHAR(2000) NULL,
 FileId UNIQUEIDENTIFIER NULL,
 CreatedByUserId UNIQUEIDENTIFIER NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(ContractId) REFERENCES Projects.Contracts(ContractId),
 FOREIGN KEY(CreatedByUserId) REFERENCES Security.Users(UserId),
 UNIQUE(ContractId,VersionNumber)
);
CREATE TABLE Projects.PaymentPlans(
 PaymentPlanId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ContractId UNIQUEIDENTIFIER NOT NULL,
 NameAr NVARCHAR(250) NOT NULL,
 NameEn NVARCHAR(250) NULL,
 IsActive BIT NOT NULL DEFAULT 1,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(ContractId) REFERENCES Projects.Contracts(ContractId)
);
CREATE TABLE Projects.PaymentPlanItems(
 PaymentPlanItemId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 PaymentPlanId UNIQUEIDENTIFIER NOT NULL,
 StageId UNIQUEIDENTIFIER NULL,
 ItemNumber INT NOT NULL,
 DescriptionAr NVARCHAR(500) NOT NULL,
 DescriptionEn NVARCHAR(500) NULL,
 CalculationType TINYINT NOT NULL DEFAULT 1, -- 1 fixed, 2 percentage
 PercentageValue DECIMAL(9,4) NULL,
 FixedAmount DECIMAL(19,4) NULL,
 DueDate DATE NULL,
 DueAfterDays INT NULL,
 IsMilestoneBased BIT NOT NULL DEFAULT 0,
 IsCustomerVisible BIT NOT NULL DEFAULT 1,
 Notes NVARCHAR(2000) NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 CHECK(CalculationType IN(1,2)),
 CHECK((CalculationType=1 AND FixedAmount IS NOT NULL AND FixedAmount>=0 AND PercentageValue IS NULL)
   OR (CalculationType=2 AND PercentageValue IS NOT NULL AND PercentageValue BETWEEN 0 AND 100 AND FixedAmount IS NULL)),
 FOREIGN KEY(PaymentPlanId) REFERENCES Projects.PaymentPlans(PaymentPlanId),
 FOREIGN KEY(StageId) REFERENCES Projects.ProjectStages(StageId),
 UNIQUE(PaymentPlanId,ItemNumber)
);
CREATE TABLE Projects.ChangeOrders(
 ChangeOrderId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ProjectId UNIQUEIDENTIFIER NOT NULL,
 ContractId UNIQUEIDENTIFIER NOT NULL,
 ChangeOrderNumber NVARCHAR(50) NOT NULL,
 Title NVARCHAR(250) NOT NULL,
 Description NVARCHAR(MAX) NULL,
 RequestedByType TINYINT NULL,
 RequestedByCustomerId UNIQUEIDENTIFIER NULL,
 SubmittedDate DATE NULL,
 DecisionDate DATE NULL,
 Status TINYINT NOT NULL DEFAULT 1, -- 1 Draft, 2 Pending, 3 Approved, 4 Rejected, 5 Cancelled
 ValueChange DECIMAL(19,4) NOT NULL DEFAULT 0,
 DurationChangeDays INT NOT NULL DEFAULT 0,
 CustomerApprovalRequired BIT NOT NULL DEFAULT 0,
 CustomerApprovedAtUtc DATETIME2(0) NULL,
 ApprovedByUserId UNIQUEIDENTIFIER NULL,
 ApprovalNotes NVARCHAR(2000) NULL,
 CreatedByUserId UNIQUEIDENTIFIER NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 RowVersion ROWVERSION,
 CHECK(Status IN(1,2,3,4,5)),
 FOREIGN KEY(ProjectId) REFERENCES Projects.Projects(ProjectId),
 FOREIGN KEY(ContractId) REFERENCES Projects.Contracts(ContractId),
 FOREIGN KEY(RequestedByCustomerId) REFERENCES Core.Customers(CustomerId),
 FOREIGN KEY(ApprovedByUserId) REFERENCES Security.Users(UserId),
 FOREIGN KEY(CreatedByUserId) REFERENCES Security.Users(UserId),
 UNIQUE(ProjectId,ChangeOrderNumber)
);
CREATE TABLE Projects.ChangeOrderItems(
 ChangeOrderItemId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ChangeOrderId UNIQUEIDENTIFIER NOT NULL,
 StageId UNIQUEIDENTIFIER NULL,
 DescriptionAr NVARCHAR(500) NOT NULL,
 DescriptionEn NVARCHAR(500) NULL,
 Quantity DECIMAL(19,4) NULL,
 UnitId UNIQUEIDENTIFIER NULL,
 UnitPrice DECIMAL(19,4) NULL,
 AmountChange DECIMAL(19,4) NOT NULL DEFAULT 0,
 DurationChangeDays INT NOT NULL DEFAULT 0,
 IsAddition BIT NOT NULL DEFAULT 1,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(ChangeOrderId) REFERENCES Projects.ChangeOrders(ChangeOrderId),
 FOREIGN KEY(StageId) REFERENCES Projects.ProjectStages(StageId),
 FOREIGN KEY(UnitId) REFERENCES Core.UnitsOfMeasure(UnitId)
);
GO

/* Finance */
CREATE TABLE Finance.CashBanks(
 CashBankId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NOT NULL,
 AccountCode NVARCHAR(50) NOT NULL,
 AccountNameAr NVARCHAR(200) NOT NULL,
 AccountNameEn NVARCHAR(200) NULL,
 AccountType TINYINT NOT NULL, -- 1 Cash, 2 Bank, 3 Wallet, 4 Gateway
 BankName NVARCHAR(200) NULL,
 AccountNumber NVARCHAR(100) NULL,
 IBAN NVARCHAR(100) NULL,
 CurrencyCode CHAR(3) NOT NULL,
 IsActive BIT NOT NULL DEFAULT 1,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(CurrencyCode) REFERENCES Core.Currencies(CurrencyCode),
 UNIQUE(CompanyId,AccountCode)
);
CREATE TABLE Finance.PaymentMethods(
 PaymentMethodId TINYINT NOT NULL PRIMARY KEY,
 Code NVARCHAR(30) NOT NULL UNIQUE,
 NameAr NVARCHAR(100) NOT NULL,
 NameEn NVARCHAR(100) NULL,
 IsElectronic BIT NOT NULL DEFAULT 0,
 IsActive BIT NOT NULL DEFAULT 1
);
CREATE TABLE Finance.ExpenseTypes(
 ExpenseTypeId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NULL,
 ExpenseCategoryId UNIQUEIDENTIFIER NOT NULL,
 Code NVARCHAR(50) NOT NULL,
 NameAr NVARCHAR(150) NOT NULL,
 NameEn NVARCHAR(150) NULL,
 IsActive BIT NOT NULL DEFAULT 1,
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(ExpenseCategoryId) REFERENCES Core.ExpenseCategories(ExpenseCategoryId)
);
CREATE TABLE Finance.Expenses(
 ExpenseId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NOT NULL,
 BranchId UNIQUEIDENTIFIER NULL,
 ProjectId UNIQUEIDENTIFIER NULL,
 ExpenseCategoryId UNIQUEIDENTIFIER NOT NULL,
 ExpenseTypeId UNIQUEIDENTIFIER NULL,
 ExpenseNumber NVARCHAR(50) NOT NULL,
 ExpenseDate DATE NOT NULL,
 Description NVARCHAR(2000) NULL,
 Amount DECIMAL(19,4) NOT NULL,
 CurrencyCode CHAR(3) NOT NULL,
 PaymentMethodId TINYINT NOT NULL,
 CashBankId UNIQUEIDENTIFIER NULL,
 PayeeName NVARCHAR(250) NULL,
 ReferenceNumber NVARCHAR(150) NULL,
 IsCompanyExpense BIT NOT NULL DEFAULT 0,
 ApprovalStatus TINYINT NOT NULL DEFAULT 1, -- 1 Draft, 2 Approved, 3 Rejected, 4 Paid
 ApprovedByUserId UNIQUEIDENTIFIER NULL,
 ApprovedAtUtc DATETIME2(0) NULL,
 PaidAtUtc DATETIME2(0) NULL,
 Notes NVARCHAR(4000) NULL,
 CreatedByUserId UNIQUEIDENTIFIER NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 RowVersion ROWVERSION,
 CHECK(Amount>0),
 CHECK((IsCompanyExpense=1 AND ProjectId IS NULL) OR (IsCompanyExpense=0 AND ProjectId IS NOT NULL)),
 CHECK(ApprovalStatus IN(1,2,3,4)),
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(BranchId) REFERENCES Core.Branches(BranchId),
 FOREIGN KEY(ProjectId) REFERENCES Projects.Projects(ProjectId),
 FOREIGN KEY(ExpenseCategoryId) REFERENCES Core.ExpenseCategories(ExpenseCategoryId),
 FOREIGN KEY(ExpenseTypeId) REFERENCES Finance.ExpenseTypes(ExpenseTypeId),
 FOREIGN KEY(CurrencyCode) REFERENCES Core.Currencies(CurrencyCode),
 FOREIGN KEY(PaymentMethodId) REFERENCES Finance.PaymentMethods(PaymentMethodId),
 FOREIGN KEY(CashBankId) REFERENCES Finance.CashBanks(CashBankId),
 FOREIGN KEY(ApprovedByUserId) REFERENCES Security.Users(UserId),
 FOREIGN KEY(CreatedByUserId) REFERENCES Security.Users(UserId),
 UNIQUE(CompanyId,ExpenseNumber)
);
CREATE TABLE Finance.CustomerPayments(
 PaymentId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NOT NULL,
 BranchId UNIQUEIDENTIFIER NULL,
 ProjectId UNIQUEIDENTIFIER NOT NULL,
 CustomerId UNIQUEIDENTIFIER NOT NULL,
 PaymentNumber NVARCHAR(50) NOT NULL,
 PaymentDate DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 Amount DECIMAL(19,4) NOT NULL,
 CurrencyCode CHAR(3) NOT NULL,
 PaymentMethodId TINYINT NOT NULL,
 CashBankId UNIQUEIDENTIFIER NULL,
 ReferenceNumber NVARCHAR(150) NULL,
 GatewayTransactionId NVARCHAR(200) NULL,
 BankName NVARCHAR(200) NULL,
 PayerName NVARCHAR(250) NULL,
 Notes NVARCHAR(4000) NULL,
 Status TINYINT NOT NULL DEFAULT 1, -- 1 Pending, 2 Confirmed, 3 Rejected, 4 Refunded
 CustomerVisible BIT NOT NULL DEFAULT 1,
 ConfirmedByUserId UNIQUEIDENTIFIER NULL,
 ConfirmedAtUtc DATETIME2(0) NULL,
 CreatedByUserId UNIQUEIDENTIFIER NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 RowVersion ROWVERSION,
 CHECK(Amount>0),
 CHECK(Status IN(1,2,3,4)),
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(BranchId) REFERENCES Core.Branches(BranchId),
 FOREIGN KEY(ProjectId) REFERENCES Projects.Projects(ProjectId),
 FOREIGN KEY(CustomerId) REFERENCES Core.Customers(CustomerId),
 FOREIGN KEY(CurrencyCode) REFERENCES Core.Currencies(CurrencyCode),
 FOREIGN KEY(PaymentMethodId) REFERENCES Finance.PaymentMethods(PaymentMethodId),
 FOREIGN KEY(CashBankId) REFERENCES Finance.CashBanks(CashBankId),
 FOREIGN KEY(ConfirmedByUserId) REFERENCES Security.Users(UserId),
 FOREIGN KEY(CreatedByUserId) REFERENCES Security.Users(UserId),
 UNIQUE(CompanyId,PaymentNumber)
);
CREATE TABLE Finance.PaymentAllocations(
 PaymentAllocationId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 PaymentId UNIQUEIDENTIFIER NOT NULL,
 PaymentPlanItemId UNIQUEIDENTIFIER NULL,
 Amount DECIMAL(19,4) NOT NULL,
 Notes NVARCHAR(1000) NULL,
 CHECK(Amount>0),
 FOREIGN KEY(PaymentId) REFERENCES Finance.CustomerPayments(PaymentId),
 FOREIGN KEY(PaymentPlanItemId) REFERENCES Projects.PaymentPlanItems(PaymentPlanItemId)
);
CREATE TABLE Finance.GatewayTransactions(
 GatewayTransactionIdPk UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NOT NULL,
 PaymentId UNIQUEIDENTIFIER NULL,
 ProviderCode NVARCHAR(50) NOT NULL,
 MerchantReference NVARCHAR(200) NOT NULL,
 ProviderReference NVARCHAR(200) NULL,
 Amount DECIMAL(19,4) NOT NULL,
 CurrencyCode CHAR(3) NOT NULL,
 Status NVARCHAR(50) NOT NULL,
 RequestPayloadJson NVARCHAR(MAX) NULL,
 ResponsePayloadJson NVARCHAR(MAX) NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 CompletedAtUtc DATETIME2(0) NULL,
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(PaymentId) REFERENCES Finance.CustomerPayments(PaymentId),
 FOREIGN KEY(CurrencyCode) REFERENCES Core.Currencies(CurrencyCode),
 UNIQUE(ProviderCode,MerchantReference)
);
CREATE TABLE Finance.ContractorPayments(
 ContractorPaymentId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NOT NULL,
 ProjectId UNIQUEIDENTIFIER NOT NULL,
 ContractorId UNIQUEIDENTIFIER NOT NULL,
 PaymentNumber NVARCHAR(50) NOT NULL,
 PaymentDate DATE NOT NULL,
 Amount DECIMAL(19,4) NOT NULL,
 CurrencyCode CHAR(3) NOT NULL,
 PaymentMethodId TINYINT NOT NULL,
 CashBankId UNIQUEIDENTIFIER NULL,
 ReferenceNumber NVARCHAR(150) NULL,
 Notes NVARCHAR(4000) NULL,
 Status TINYINT NOT NULL DEFAULT 1,
 CreatedByUserId UNIQUEIDENTIFIER NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 CHECK(Amount>0),
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(ProjectId) REFERENCES Projects.Projects(ProjectId),
 FOREIGN KEY(ContractorId) REFERENCES Core.Contractors(ContractorId),
 FOREIGN KEY(CurrencyCode) REFERENCES Core.Currencies(CurrencyCode),
 FOREIGN KEY(PaymentMethodId) REFERENCES Finance.PaymentMethods(PaymentMethodId),
 FOREIGN KEY(CashBankId) REFERENCES Finance.CashBanks(CashBankId),
 FOREIGN KEY(CreatedByUserId) REFERENCES Security.Users(UserId),
 UNIQUE(CompanyId,PaymentNumber)
);
CREATE TABLE Finance.PaymentScheduleSnapshot(
 PaymentScheduleSnapshotId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ProjectId UNIQUEIDENTIFIER NOT NULL,
 ContractId UNIQUEIDENTIFIER NOT NULL,
 PaymentPlanItemId UNIQUEIDENTIFIER NULL,
 DescriptionAr NVARCHAR(500) NOT NULL,
 DueDate DATE NULL,
 AmountDue DECIMAL(19,4) NOT NULL,
 AmountPaid DECIMAL(19,4) NOT NULL DEFAULT 0,
 Status TINYINT NOT NULL DEFAULT 1,
 CustomerVisible BIT NOT NULL DEFAULT 1,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 CHECK(AmountDue>=0 AND AmountPaid>=0 AND AmountPaid<=AmountDue),
 FOREIGN KEY(ProjectId) REFERENCES Projects.Projects(ProjectId),
 FOREIGN KEY(ContractId) REFERENCES Projects.Contracts(ContractId),
 FOREIGN KEY(PaymentPlanItemId) REFERENCES Projects.PaymentPlanItems(PaymentPlanItemId)
);
GO

/* Files */
CREATE TABLE Files.StoredFiles(
 FileId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NULL,
 OriginalFileName NVARCHAR(260) NOT NULL,
 StoredFileName NVARCHAR(260) NOT NULL,
 StorageProvider NVARCHAR(50) NOT NULL DEFAULT N'Local',
 StoragePath NVARCHAR(1000) NOT NULL,
 ContentType NVARCHAR(150) NULL,
 Extension NVARCHAR(20) NULL,
 SizeBytes BIGINT NULL,
 Sha256Hash VARBINARY(32) NULL,
 IsImage BIT NOT NULL DEFAULT 0,
 WidthPixels INT NULL,
 HeightPixels INT NULL,
 ThumbnailPath NVARCHAR(1000) NULL,
 IsPublic BIT NOT NULL DEFAULT 0,
 IsDeleted BIT NOT NULL DEFAULT 0,
 UploadedByUserId UNIQUEIDENTIFIER NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(UploadedByUserId) REFERENCES Security.Users(UserId)
);
CREATE TABLE Files.EntityFiles(
 EntityFileId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 FileId UNIQUEIDENTIFIER NOT NULL,
 EntityType NVARCHAR(100) NOT NULL,
 EntityId UNIQUEIDENTIFIER NOT NULL,
 DisplayOrder INT NOT NULL DEFAULT 0,
 CaptionAr NVARCHAR(1000) NULL,
 CaptionEn NVARCHAR(1000) NULL,
 CustomerVisible BIT NOT NULL DEFAULT 0,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(FileId) REFERENCES Files.StoredFiles(FileId),
 UNIQUE(EntityType,EntityId,DisplayOrder)
);
CREATE TABLE Files.ProgressUpdateImages(
 ProgressUpdateImageId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ProgressUpdateId UNIQUEIDENTIFIER NOT NULL,
 FileId UNIQUEIDENTIFIER NOT NULL,
 ImageOrder TINYINT NOT NULL,
 CaptionAr NVARCHAR(1000) NULL,
 CaptionEn NVARCHAR(1000) NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 CHECK(ImageOrder BETWEEN 1 AND 5),
 FOREIGN KEY(ProgressUpdateId) REFERENCES Projects.ProgressUpdates(ProgressUpdateId),
 FOREIGN KEY(FileId) REFERENCES Files.StoredFiles(FileId),
 UNIQUE(ProgressUpdateId,ImageOrder),
 UNIQUE(ProgressUpdateId,FileId)
);
GO
CREATE OR ALTER TRIGGER Files.TR_ProgressUpdateImages_Max5
ON Files.ProgressUpdateImages
AFTER INSERT, UPDATE
AS
BEGIN
 SET NOCOUNT ON;
 IF EXISTS(
   SELECT P.ProgressUpdateId
   FROM Files.ProgressUpdateImages P
   INNER JOIN (SELECT DISTINCT ProgressUpdateId FROM inserted) I ON I.ProgressUpdateId=P.ProgressUpdateId
   GROUP BY P.ProgressUpdateId
   HAVING COUNT(*)>5
 )
 BEGIN
   ROLLBACK TRANSACTION;
   THROW 51001,N'كل تحديث إنجاز يسمح بحد أقصى 5 صور.',1;
 END
END;
GO
CREATE TABLE Files.DocumentTypes(
 DocumentTypeId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NULL,
 Code NVARCHAR(50) NOT NULL,
 NameAr NVARCHAR(150) NOT NULL,
 NameEn NVARCHAR(150) NULL,
 IsCustomerVisible BIT NOT NULL DEFAULT 0,
 IsActive BIT NOT NULL DEFAULT 1,
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId)
);
CREATE TABLE Files.BusinessDocuments(
 BusinessDocumentId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NOT NULL,
 ProjectId UNIQUEIDENTIFIER NULL,
 CustomerId UNIQUEIDENTIFIER NULL,
 DocumentTypeId UNIQUEIDENTIFIER NULL,
 DocumentNumber NVARCHAR(100) NULL,
 DocumentDate DATE NULL,
 TitleAr NVARCHAR(250) NOT NULL,
 TitleEn NVARCHAR(250) NULL,
 Description NVARCHAR(4000) NULL,
 FileId UNIQUEIDENTIFIER NOT NULL,
 CustomerVisible BIT NOT NULL DEFAULT 0,
 CreatedByUserId UNIQUEIDENTIFIER NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(ProjectId) REFERENCES Projects.Projects(ProjectId),
 FOREIGN KEY(CustomerId) REFERENCES Core.Customers(CustomerId),
 FOREIGN KEY(DocumentTypeId) REFERENCES Files.DocumentTypes(DocumentTypeId),
 FOREIGN KEY(FileId) REFERENCES Files.StoredFiles(FileId),
 FOREIGN KEY(CreatedByUserId) REFERENCES Security.Users(UserId)
);
GO

/* Communication */
CREATE TABLE Communication.NotificationTemplates(
 NotificationTemplateId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NULL,
 TemplateCode NVARCHAR(100) NOT NULL,
 NameAr NVARCHAR(200) NOT NULL,
 NameEn NVARCHAR(200) NULL,
 Channel TINYINT NOT NULL, -- 1 InApp 2 Push 3 WhatsApp 4 Email 5 SMS
 SubjectTemplate NVARCHAR(500) NULL,
 BodyTemplate NVARCHAR(MAX) NOT NULL,
 IsAutomatic BIT NOT NULL DEFAULT 1,
 IsActive BIT NOT NULL DEFAULT 1,
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 UNIQUE(CompanyId,TemplateCode)
);
CREATE TABLE Communication.NotificationRules(
 NotificationRuleId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NOT NULL,
 EventCode NVARCHAR(100) NOT NULL,
 NotificationTemplateId UNIQUEIDENTIFIER NOT NULL,
 IsEnabled BIT NOT NULL DEFAULT 1,
 SendToCustomer BIT NOT NULL DEFAULT 1,
 SendToStaff BIT NOT NULL DEFAULT 0,
 SendAutomatically BIT NOT NULL DEFAULT 1,
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(NotificationTemplateId) REFERENCES Communication.NotificationTemplates(NotificationTemplateId),
 UNIQUE(CompanyId,EventCode)
);
CREATE TABLE Communication.Notifications(
 NotificationId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NOT NULL,
 UserId UNIQUEIDENTIFIER NULL,
 CustomerId UNIQUEIDENTIFIER NULL,
 ProjectId UNIQUEIDENTIFIER NULL,
 EventCode NVARCHAR(100) NULL,
 Channel TINYINT NOT NULL,
 Title NVARCHAR(300) NOT NULL,
 Body NVARCHAR(MAX) NOT NULL,
 IsRead BIT NOT NULL DEFAULT 0,
 ScheduledAtUtc DATETIME2(0) NULL,
 SentAtUtc DATETIME2(0) NULL,
 DeliveredAtUtc DATETIME2(0) NULL,
 FailedAtUtc DATETIME2(0) NULL,
 ErrorMessage NVARCHAR(2000) NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(UserId) REFERENCES Security.Users(UserId),
 FOREIGN KEY(CustomerId) REFERENCES Core.Customers(CustomerId),
 FOREIGN KEY(ProjectId) REFERENCES Projects.Projects(ProjectId)
);
CREATE TABLE Communication.WhatsAppSettings(
 WhatsAppSettingId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NOT NULL UNIQUE,
 ProviderName NVARCHAR(100) NOT NULL,
 ApiBaseUrl NVARCHAR(500) NULL,
 SenderPhoneNumber NVARCHAR(50) NULL,
 AccountIdentifier NVARCHAR(200) NULL,
 AccessTokenEncrypted VARBINARY(MAX) NULL,
 IsEnabled BIT NOT NULL DEFAULT 0,
 AllowAutomaticSending BIT NOT NULL DEFAULT 0,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId)
);
CREATE TABLE Communication.WhatsAppMessages(
 WhatsAppMessageId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NOT NULL,
 CustomerId UNIQUEIDENTIFIER NULL,
 UserId UNIQUEIDENTIFIER NULL,
 ProjectId UNIQUEIDENTIFIER NULL,
 NotificationId UNIQUEIDENTIFIER NULL,
 RecipientNumber NVARCHAR(50) NOT NULL,
 MessageText NVARCHAR(MAX) NOT NULL,
 ProviderMessageId NVARCHAR(200) NULL,
 SendMode TINYINT NOT NULL DEFAULT 1, -- 1 Auto 2 Manual
 Status TINYINT NOT NULL DEFAULT 1, -- 1 Queued 2 Sent 3 Delivered 4 Failed
 ScheduledAtUtc DATETIME2(0) NULL,
 SentAtUtc DATETIME2(0) NULL,
 DeliveredAtUtc DATETIME2(0) NULL,
 ErrorMessage NVARCHAR(2000) NULL,
 CreatedByUserId UNIQUEIDENTIFIER NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(CustomerId) REFERENCES Core.Customers(CustomerId),
 FOREIGN KEY(UserId) REFERENCES Security.Users(UserId),
 FOREIGN KEY(ProjectId) REFERENCES Projects.Projects(ProjectId),
 FOREIGN KEY(NotificationId) REFERENCES Communication.Notifications(NotificationId),
 FOREIGN KEY(CreatedByUserId) REFERENCES Security.Users(UserId)
);
CREATE TABLE Communication.CustomerNotes(
 CustomerNoteId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CustomerId UNIQUEIDENTIFIER NOT NULL,
 ProjectId UNIQUEIDENTIFIER NULL,
 NoteType TINYINT NOT NULL DEFAULT 1,
 Title NVARCHAR(250) NULL,
 NoteText NVARCHAR(4000) NOT NULL,
 CustomerVisible BIT NOT NULL DEFAULT 0,
 CreatedByUserId UNIQUEIDENTIFIER NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(CustomerId) REFERENCES Core.Customers(CustomerId),
 FOREIGN KEY(ProjectId) REFERENCES Projects.Projects(ProjectId),
 FOREIGN KEY(CreatedByUserId) REFERENCES Security.Users(UserId)
);
GO

/* Audit + App */
CREATE TABLE Audit.AuditLogs(
 AuditLogId BIGINT IDENTITY(1,1) PRIMARY KEY,
 CompanyId UNIQUEIDENTIFIER NULL,
 UserId UNIQUEIDENTIFIER NULL,
 ActionType NVARCHAR(50) NOT NULL,
 EntityName NVARCHAR(150) NOT NULL,
 EntityId UNIQUEIDENTIFIER NULL,
 OldValuesJson NVARCHAR(MAX) NULL,
 NewValuesJson NVARCHAR(MAX) NULL,
 IpAddress NVARCHAR(64) NULL,
 UserAgent NVARCHAR(1000) NULL,
 CorrelationId NVARCHAR(100) NULL,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(UserId) REFERENCES Security.Users(UserId)
);
CREATE TABLE App.Settings(
 SettingId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NULL,
 SettingKey NVARCHAR(200) NOT NULL,
 SettingValue NVARCHAR(MAX) NULL,
 ValueType NVARCHAR(30) NOT NULL DEFAULT N'String',
 IsEncrypted BIT NOT NULL DEFAULT 0,
 IsPublic BIT NOT NULL DEFAULT 0,
 UpdatedByUserId UNIQUEIDENTIFIER NULL,
 UpdatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId),
 FOREIGN KEY(UpdatedByUserId) REFERENCES Security.Users(UserId),
 UNIQUE(CompanyId,SettingKey)
);
CREATE TABLE App.ApiClients(
 ApiClientId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 CompanyId UNIQUEIDENTIFIER NULL,
 ClientName NVARCHAR(200) NOT NULL,
 ClientType TINYINT NOT NULL DEFAULT 1, -- 1 Desktop, 2 Mobile, 3 Integration, 4 Internal
 ClientKeyHash VARBINARY(64) NULL,
 IsActive BIT NOT NULL DEFAULT 1,
 CreatedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 LastUsedAtUtc DATETIME2(0) NULL,
 FOREIGN KEY(CompanyId) REFERENCES Core.Companies(CompanyId)
);
CREATE TABLE App.DatabaseMigrations(
 MigrationId BIGINT IDENTITY(1,1) PRIMARY KEY,
 MigrationKey NVARCHAR(200) NOT NULL UNIQUE,
 VersionNumber NVARCHAR(50) NOT NULL,
 Description NVARCHAR(500) NULL,
 AppliedAtUtc DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
 AppliedBy NVARCHAR(200) NULL,
 Checksum VARBINARY(32) NULL,
 ExecutionMilliseconds INT NULL
);
GO

/* Seed */
INSERT INTO Core.Currencies(CurrencyCode,NameAr,NameEn,DecimalDigits) VALUES
('IQD',N'الدينار العراقي',N'Iraqi Dinar',0),('USD',N'الدولار الأمريكي',N'US Dollar',2);
INSERT INTO Core.UnitsOfMeasure(Code,NameAr,NameEn) VALUES
('PCS',N'قطعة',N'Piece'),('M',N'متر',N'Meter'),('M2',N'متر مربع',N'Square Meter'),('M3',N'متر مكعب',N'Cubic Meter'),('KG',N'كيلوغرام',N'Kilogram');
INSERT INTO Core.ProjectStatuses(Code,NameAr,NameEn,SortOrder,IsSystem) VALUES
('NEW',N'جديد',N'New',10,1),('CONTRACTED',N'متعاقد عليه',N'Contracted',20,1),('IN_PROGRESS',N'قيد التنفيذ',N'In Progress',30,1),('ON_HOLD',N'متوقف',N'On Hold',40,1),('COMPLETED',N'مكتمل',N'Completed',50,1),('CANCELLED',N'ملغي',N'Cancelled',60,1);
INSERT INTO Finance.PaymentMethods(PaymentMethodId,Code,NameAr,NameEn,IsElectronic) VALUES
(1,'CASH',N'نقدي',N'Cash',0),(2,'BANK_TRANSFER',N'حوالة بنكية',N'Bank Transfer',0),(3,'ELECTRONIC',N'دفع إلكتروني',N'Electronic Payment',1),(4,'CARD',N'بطاقة',N'Card',1),(5,'OTHER',N'أخرى',N'Other',0);
INSERT INTO Security.Roles(RoleCode,NameAr,NameEn,IsSystemRole) VALUES
('SUPER_ADMIN',N'مدير النظام',N'Super Admin',1),('COMPANY_ADMIN',N'مدير الشركة',N'Company Manager',1),('PROJECT_MANAGER',N'مدير مشاريع',N'Project Manager',1),('ACCOUNTANT',N'المحاسب',N'Accountant',1),('SITE_SUPERVISOR',N'مشرف موقع',N'Site Supervisor',1),('CUSTOMER',N'عميل',N'Customer',1);
INSERT INTO Core.ExpenseCategories(Code,NameAr,NameEn,ScopeType) VALUES
('LABOR',N'عمالة',N'Labor',2),('SITE',N'مصاريف موقع',N'Site Expense',2),('TRANSPORT',N'نقل',N'Transport',1),('SALARIES',N'رواتب',N'Salaries',3),('RENT',N'إيجار',N'Rent',3),('UTILITIES',N'خدمات ومرافق',N'Utilities',3),('ADMIN',N'إدارية',N'Administration',3);
INSERT INTO App.DatabaseMigrations(MigrationKey,VersionNumber,Description,AppliedBy) VALUES('InitialCreate','1.0.0',N'النسخة الأولية الكاملة لقاعدة نظام إدارة شركات البناء',SUSER_SNAME());
GO

/* Indexes */
CREATE INDEX IX_Branches_Company ON Core.Branches(CompanyId,IsActive);
CREATE INDEX IX_Users_CompanyBranch ON Security.Users(CompanyId,BranchId,IsActive);
CREATE INDEX IX_Users_Customer ON Security.Users(CustomerId,UserType,IsActive);
CREATE INDEX IX_UserDevices_User ON Security.UserDevices(UserId,IsActive);
CREATE INDEX IX_Customers_CompanyName ON Core.Customers(CompanyId,FullNameAr);
CREATE INDEX IX_Contractors_CompanyName ON Core.Contractors(CompanyId,NameAr);
CREATE INDEX IX_Projects_CompanyStatus ON Projects.Projects(CompanyId,ProjectStatusId,IsArchived);
CREATE INDEX IX_Projects_Customer ON Projects.Projects(CustomerId,IsArchived);
CREATE INDEX IX_ProjectStages_Project ON Projects.ProjectStages(ProjectId,SortOrder);
CREATE INDEX IX_WorkItems_Stage ON Projects.StageWorkItems(StageId,SortOrder);
CREATE INDEX IX_ProgressUpdates_ProjectDate ON Projects.ProgressUpdates(ProjectId,UpdateDate DESC);
CREATE INDEX IX_ProgressUpdates_Visible ON Projects.ProgressUpdates(ProjectId,CustomerVisible,UpdateDate DESC);
CREATE INDEX IX_Contracts_Project ON Projects.Contracts(ProjectId,Status);
CREATE INDEX IX_PaymentPlanItems_Plan ON Projects.PaymentPlanItems(PaymentPlanId,DueDate);
CREATE INDEX IX_ChangeOrders_ProjectStatus ON Projects.ChangeOrders(ProjectId,Status,SubmittedDate);
CREATE INDEX IX_Expenses_ProjectDate ON Finance.Expenses(ProjectId,ExpenseDate);
CREATE INDEX IX_Expenses_CompanyDate ON Finance.Expenses(CompanyId,ExpenseDate);
CREATE INDEX IX_CustomerPayments_ProjectDate ON Finance.CustomerPayments(ProjectId,PaymentDate);
CREATE INDEX IX_CustomerPayments_CustomerDate ON Finance.CustomerPayments(CustomerId,PaymentDate);
CREATE INDEX IX_ContractorPayments_ProjectDate ON Finance.ContractorPayments(ProjectId,PaymentDate);
CREATE INDEX IX_EntityFiles_Entity ON Files.EntityFiles(EntityType,EntityId,DisplayOrder);
CREATE INDEX IX_ProgressUpdateImages_Update ON Files.ProgressUpdateImages(ProgressUpdateId,ImageOrder);
CREATE INDEX IX_BusinessDocuments_Project ON Files.BusinessDocuments(ProjectId,CustomerVisible);
CREATE INDEX IX_Notifications_UserUnread ON Communication.Notifications(UserId,IsRead,CreatedAtUtc DESC);
CREATE INDEX IX_Notifications_CustomerUnread ON Communication.Notifications(CustomerId,IsRead,CreatedAtUtc DESC);
CREATE INDEX IX_WhatsAppMessages_Status ON Communication.WhatsAppMessages(Status,ScheduledAtUtc);
CREATE INDEX IX_AuditLogs_CompanyDate ON Audit.AuditLogs(CompanyId,CreatedAtUtc DESC);
CREATE INDEX IX_AuditLogs_Entity ON Audit.AuditLogs(EntityName,EntityId,CreatedAtUtc DESC);
GO

/* Portal-safe views */
CREATE OR ALTER VIEW Projects.vw_CustomerProjectSummary AS
SELECT P.ProjectId,P.CompanyId,P.BranchId,P.CustomerId,P.ProjectCode,P.ProjectName,P.ProjectType,P.Address,P.City,
       P.StartDate,P.PlannedEndDate,P.ActualEndDate,P.OverallProgressPercent,P.OriginalContractValue,P.CurrentContractValue,
       C.NameAr AS CompanyNameAr,CU.FullNameAr AS CustomerNameAr,S.NameAr AS ProjectStatusAr
FROM Projects.Projects P
JOIN Core.Companies C ON C.CompanyId=P.CompanyId
JOIN Core.Customers CU ON CU.CustomerId=P.CustomerId
JOIN Core.ProjectStatuses S ON S.ProjectStatusId=P.ProjectStatusId;
GO
CREATE OR ALTER VIEW Finance.vw_ProjectFinancialSummary AS
SELECT P.ProjectId,P.CompanyId,P.ProjectCode,P.ProjectName,P.CustomerId,
       ISNULL(P.CurrentContractValue,0) ContractValue,
       ISNULL(E.ProjectExpenses,0) ProjectExpenses,
       ISNULL(CP.CustomerPayments,0) ConfirmedCustomerPayments,
       ISNULL(KP.ContractorPayments,0) ConfirmedContractorPayments,
       ISNULL(P.CurrentContractValue,0)-ISNULL(E.ProjectExpenses,0)-ISNULL(KP.ContractorPayments,0) ProjectProfitBeforeCompanyOverhead,
       ISNULL(P.CurrentContractValue,0)-ISNULL(CP.CustomerPayments,0) CustomerBalance
FROM Projects.Projects P
OUTER APPLY(SELECT SUM(Amount) ProjectExpenses FROM Finance.Expenses X WHERE X.ProjectId=P.ProjectId AND X.IsCompanyExpense=0 AND X.ApprovalStatus=4) E
OUTER APPLY(SELECT SUM(Amount) CustomerPayments FROM Finance.CustomerPayments X WHERE X.ProjectId=P.ProjectId AND X.Status=2) CP
OUTER APPLY(SELECT SUM(Amount) ContractorPayments FROM Finance.ContractorPayments X WHERE X.ProjectId=P.ProjectId AND X.Status=2) KP;
GO
CREATE OR ALTER VIEW Security.vw_CustomerPortalProjects AS
SELECT U.UserId,U.CustomerId,P.ProjectId,P.ProjectCode,P.ProjectName,P.OverallProgressPercent,P.CurrentContractValue,P.StartDate,P.PlannedEndDate,S.NameAr StatusNameAr
FROM Security.Users U
JOIN Core.Customers C ON C.CustomerId=U.CustomerId
JOIN Projects.Projects P ON P.CustomerId=C.CustomerId
JOIN Core.ProjectStatuses S ON S.ProjectStatusId=P.ProjectStatusId
WHERE U.UserType=2 AND U.IsActive=1 AND C.IsActive=1 AND P.IsArchived=0;
GO

/* Progress recalculation procedures */
CREATE OR ALTER PROCEDURE Projects.usp_RecalculateProjectProgress @ProjectId UNIQUEIDENTIFIER AS
BEGIN
 SET NOCOUNT ON;
 DECLARE @Progress DECIMAL(5,2);
 SELECT @Progress=CASE WHEN SUM(ISNULL(WeightPercent,0))>0
  THEN SUM(ISNULL(ProgressPercent,0)*ISNULL(WeightPercent,0))/NULLIF(SUM(ISNULL(WeightPercent,0)),0)
  ELSE AVG(CAST(ISNULL(ProgressPercent,0) AS DECIMAL(10,4))) END
 FROM Projects.ProjectStages WHERE ProjectId=@ProjectId AND IsActive=1 AND ParentStageId IS NULL;
 UPDATE Projects.Projects SET OverallProgressPercent=ISNULL(@Progress,0),UpdatedAtUtc=SYSUTCDATETIME() WHERE ProjectId=@ProjectId;
END;
GO
CREATE OR ALTER PROCEDURE Projects.usp_RecalculateStageProgress @StageId UNIQUEIDENTIFIER AS
BEGIN
 SET NOCOUNT ON;
 DECLARE @Mode TINYINT,@ProjectId UNIQUEIDENTIFIER,@Progress DECIMAL(5,2);
 SELECT @Mode=ProgressCalculationMode,@ProjectId=ProjectId FROM Projects.ProjectStages WHERE StageId=@StageId;
 IF @Mode=1 RETURN;
 SELECT @Progress=CASE WHEN @Mode=2 AND SUM(ISNULL(WeightPercent,0))>0
  THEN SUM(ISNULL(ProgressPercent,0)*ISNULL(WeightPercent,0))/NULLIF(SUM(ISNULL(WeightPercent,0)),0)
  ELSE AVG(CAST(ISNULL(ProgressPercent,0) AS DECIMAL(10,4))) END
 FROM Projects.StageWorkItems WHERE StageId=@StageId AND IsActive=1;
 UPDATE Projects.ProjectStages SET ProgressPercent=ISNULL(@Progress,0),UpdatedAtUtc=SYSUTCDATETIME() WHERE StageId=@StageId;
 EXEC Projects.usp_RecalculateProjectProgress @ProjectId=@ProjectId;
END;
GO
